version: 2
updates:
  # Prüft wöchentlich auf Updates im Dockerfile (z. B. Base-Image debian)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  # Prüft wöchentlich auf Updates in deinen Rust Crates (Cargo.toml)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"