version: 2
updates:
  # Dockerfile Base-Images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      docker-dependencies:
        patterns:
          - "*"

  # Cargo Crates (Rust)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      cargo-dependencies:
        patterns:
          - "*"